version: "3.7"
services:
  app:
    image: 1121872835/amy-ceresyo:qa
    container_name: ceresyo-app-container
    ports:
      - 8081:80
    env_file:
      - /home/adminqa/environments/ceresyo-env/.env
    networks:
      - NetCeresYo

  mariadb:
    image: mariadb:10.9
    container_name: ceresyo-db-container
    restart: unless-stopped
    ports:
      - 33069:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ceres_yo_db
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    networks:
      - NetCeresYo

networks:
  NetCeresYo:
    driver: bridge

volumes:
  db_data:
