version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: ceresyo-app-container
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - ${HOME}/environments/ceresyo-env/.env
    user: "www-data"
    networks:
      - NetCeresYo
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.23-alpine
    container_name: ceresyo-server-container
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html:cached
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - NetCeresYo

  mariadb:
    image: mariadb:10.9
    container_name: ceresyo-db-container
    restart: unless-stopped
    ports:
      - 33069:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ceres_yo_db
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    networks:
      - NetCeresYo

networks:
  NetCeresYo:
    driver: bridge

volumes:
  db_data:
