version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: ceresyo-app-container
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html:cached
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    env_file:
      - ${HOME}/environments/ceresyo-env/.env
    networks:
      - NetCeresYo
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]

  mariadb:
    image: mariadb:10.9
    container_name: ceresyo-db-container
    restart: unless-stopped
    ports:
      - "33069:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ceres_yo_db
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    networks:
      - NetCeresYo

networks:
  NetCeresYo:
    driver: bridge

volumes:
  vendor:
  node_modules:
  db_data:
