version: "3.7" # version del docker-compose(?)
services:
  nginx: # 1er servicio: nginx
    image: nginx:1.23-alpine # imagen de docker hub que vamos a usar
    container_name: ceresyo-server-container # nombre para referirse al servicio
    ports:
      - 8081:80 # puerto de mi pc:puerto del servicio
    volumes:
      - ./:/var/www/html # carpeta local/ vincula a carpeta de nginx
      - ./nginx:/etc/nginx/conf.d/ # archivo local / reflejado en archivo de la imagen
    depends_on: # para correr este servicio debe estar corriendo php y mysql antes
      - app
    networks: # la red que los conecta se llama NetCeresYo
      - NetCeresYo

  app: # 2do servicio
    build: #este se construira aqui mismo
      context: ./ # ruta de referencia ./
      dockerfile: Dockerfile # nombre del archivo de configuracion de la imagen
    container_name: ceresyo-app-container #
    restart: unless-stopped
    working_dir: /var/www/html
    volumes: # carpeta de proyecto local : carpeta del container que da vida a los archivos PHP
      - ./:/var/www/html
    user: "www-data"
    env_file:
    - ${HOME}/environments/ceresyo-env/.env
    networks:
      - NetCeresYo # red

networks: # declaracion de la red
  NetCeresYo:
    driver: bridge 